server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Tenta servir o arquivo real ($uri), depois tenta a pasta ($uri/)
        # Se não achar nada, serve o index.html (isso permite o F5 no React)
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Garante que erros de favicon ou assets não quebrem o log
    location = /favicon.ico { access_log off; log_not_found off; }
}}